apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
spec: 
  replicas: 2 
  selector:
    matchLabels:
      app: $APP_NAME 
  template:
    metadata:
      labels: 
        app: $APP_NAME
    spec: 
      imagePullSecrets: 
      - name: docker-authentication-ecr
      containers:
      - name: $APP_NAME
        image: $IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env: 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: java-secret
              key: DB_USER
        - name: DB_NAME 
          valueFrom: 
            secretKeyRef:
              name: java-secret
              key: DB_NAME
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: java-configmap
              key: database_server
        - name: DB_PWD
          valueFrom: 
            secretKeyRef:
              name: mysql
              key: mysql-password

---

apiVersion: v1
kind: Service
metadata: 
  name: java-app-service
spec:
  selector:
    app: $APP_NAME
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

      